force_torque:
  left_ankle_ft:
    sensor_joint: leg_left_6_joint
    frame: left_sole_link
  right_ankle_ft:
    sensor_joint: leg_right_6_joint
    frame: right_sole_link
  left_wrist_ft:
    sensor_joint: arm_left_7_joint
    frame: wrist_left_ft_link
  right_wrist_ft:
    sensor_joint: arm_right_7_joint
    frame: wrist_right_ft_link

imu:
  base_imu:
    frame: base_link

