right_hand_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - hand_right_index_joint
    - hand_right_middle_joint
    - hand_right_thumb_joint

  constraints:
    goal_time: &goal_time_constraint 0.6
    stopped_velocity_tolerance: &stopped_velocity_constraint 20.0 # NOTE: To overcome Gazebo bug
    hand_right_index_joint:
      goal: &goal_pos_constraint 0.02
    hand_right_middle_joint:
      goal: *goal_pos_constraint
    hand_right_thumb:
      goal: *goal_pos_constraint

  stop_trajectory_duration: 0.0

left_hand_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - hand_left_index_joint
    - hand_left_middle_joint
    - hand_left_thumb_joint

  constraints:
    goal_time: *goal_time_constraint
    stopped_velocity_tolerance: *stopped_velocity_constraint
    hand_left_index_joint:
      goal: *goal_pos_constraint
    hand_left_middle_joint:
      goal: *goal_pos_constraint
    hand_left_thumb:
      goal: *goal_pos_constraint

  stop_trajectory_duration: 0.0