right_arm_torso_controller:
  type: "robot_mechanism_controllers/JointTrajectoryActionController"
  joints: &arm_right_torso_joints
    - torso_1_joint
    - torso_2_joint
    - arm_right_1_joint
    - arm_right_2_joint
    - arm_right_3_joint
    - arm_right_4_joint
    - arm_right_5_joint
    - arm_right_6_joint
    - arm_right_7_joint
  gains:
    torso_1_joint:                  {p: 1500.0, d: 800.0, i: 30, i_clamp: 6.0}
    torso_2_joint:                  {p: 1500.0, d: 800.0, i: 30, i_clamp: 6.0}
    arm_right_1_joint: &arm_1_gains {p: 800, d: 500, i: 20, i_clamp: 3.0}
    arm_right_2_joint: &arm_2_gains {p: 800, d: 500, i: 20, i_clamp: 3.0}
    arm_right_3_joint: &arm_3_gains {p: 600, d: 350, i: 15, i_clamp: 2.0}
    arm_right_4_joint: &arm_4_gains {p: 800, d: 500, i: 20, i_clamp: 3.0}
    arm_right_5_joint: &arm_5_gains {p: 100, d: 80, i: 10, i_clamp: 1.5}
    arm_right_6_joint: &arm_6_gains {p: 100, d: 80, i: 10, i_clamp: 1.5}
    arm_right_7_joint: &arm_7_gains {p: 100, d: 80, i: 10, i_clamp: 1.5}
  joint_trajectory_action_node:
    joints: *arm_right_torso_joints
    constraints:
      goal_time: &goal_time_constraint 0.6
      arm_right_1_joint:
        goal: &goal_pos_constraint 0.02
      torso_2_joint:
        goal: *goal_pos_constraint
      arm_right_1_joint:
        goal: *goal_pos_constraint
      arm_right_2_joint:
        goal: *goal_pos_constraint
      arm_right_3_joint:
        goal: *goal_pos_constraint
      arm_right_4_joint:
        goal: *goal_pos_constraint
      arm_right_5_joint:
        goal: *goal_pos_constraint
      arm_right_6_joint:
        goal: *goal_pos_constraint
      arm_right_7_joint:
        goal: *goal_pos_constraint

left_arm_controller:
  type: "robot_mechanism_controllers/JointTrajectoryActionController"
  joints: &arm_left_joints
    - arm_left_1_joint
    - arm_left_2_joint
    - arm_left_3_joint
    - arm_left_4_joint
    - arm_left_5_joint
    - arm_left_6_joint
    - arm_left_7_joint
  gains:
    arm_left_1_joint: *arm_1_gains
    arm_left_2_joint: *arm_2_gains
    arm_left_3_joint: *arm_3_gains
    arm_left_4_joint: *arm_4_gains
    arm_left_5_joint: *arm_5_gains
    arm_left_6_joint: *arm_6_gains
    arm_left_7_joint: *arm_7_gains
  joint_trajectory_action_node:
    joints: *arm_left_joints
    constraints:
      goal_time: *goal_time_constraint
      arm_left_1_joint:
        goal: *goal_pos_constraint
      arm_left_2_joint:
        goal: *goal_pos_constraint
      arm_left_3_joint:
        goal: *goal_pos_constraint
      arm_left_4_joint:
        goal: *goal_pos_constraint
      arm_left_5_joint:
        goal: *goal_pos_constraint
      arm_left_6_joint:
        goal: *goal_pos_constraint
      arm_left_7_joint:
        goal: *goal_pos_constraint

head_traj_controller:
  type: "robot_mechanism_controllers/JointTrajectoryActionController"
  joints: &head_joints
    - head_1_joint
    - head_2_joint
  gains:
    head_1_joint: {p: 300, d: 250, i: 10, i_clamp: 1.5}
    head_2_joint: {p: 300, d: 250, i: 10, i_clamp: 1.5}
  joint_trajectory_action_node:
    joints: *head_joints
    constraints:
      goal_time: 0.6
      head_1_joint:
        goal: 0.02
      head_2_joint:
        goal: 0.02

right_hand_controller:
  type: "robot_mechanism_controllers/JointTrajectoryActionController"
  joints: &hand_right_joints
    - hand_right_thumb_joint
    - hand_right_index_1_joint
    - hand_right_middle_1_joint
  gains:
    hand_right_thumb_joint:    &thumb_gains    {p: 200.0, d: 2.0, i: 1.0, i_clamp: 1.0}
    hand_right_index_1_joint:  &finger_1_gains {p: 200.0, d: 2.0, i: 1.0, i_clamp: 1.0}
    hand_right_middle_1_joint: *finger_1_gains
  joint_trajectory_action_node:
    joints: *hand_right_joints
    constraints:
      goal_time: *goal_time_constraint
      hand_right_thumb_joint:
        goal: *goal_pos_constraint
      hand_right_index_1_joint:
        goal: *goal_pos_constraint
      hand_right_middle_1_joint:
        goal: *goal_pos_constraint

left_hand_controller:
  type: "robot_mechanism_controllers/JointTrajectoryActionController"
  joints: &hand_left_joints
    - hand_left_thumb_joint
    - hand_left_index_1_joint
    - hand_left_middle_1_joint
  gains:
    hand_left_thumb_joint:    *thumb_gains
    hand_left_index_1_joint:  *finger_1_gains
    hand_left_middle_1_joint: *finger_1_gains
  joint_trajectory_action_node:
    joints: *hand_left_joints
    constraints:
      goal_time: *goal_time_constraint
      hand_left_thumb_joint:
        goal: *goal_pos_constraint
      hand_left_index_1_joint:
        goal: *goal_pos_constraint
      hand_left_middle_1_joint:
        goal: *goal_pos_constraint

lower_body_controller:
  type: "robot_mechanism_controllers/JointTrajectoryActionController"
  joints: &leg_joints
    - leg_left_1_joint
    - leg_left_2_joint
    - leg_left_3_joint
    - leg_left_4_joint
    - leg_left_5_joint
    - leg_left_6_joint
    - leg_right_1_joint
    - leg_right_2_joint
    - leg_right_3_joint
    - leg_right_4_joint
    - leg_right_5_joint
    - leg_right_6_joint
  gains:
    leg_left_1_joint:  &leg_1_gains {p:  1000.0, d: 2.0, i:  1.0, i_clamp:   10.0, torque_clamp: 50}
    leg_left_2_joint:  &leg_2_gains {p:  1000.0, d: 2.0, i:  1.0, i_clamp:   10.0, torque_clamp: 60}
    leg_left_3_joint:  &leg_3_gains {p:  3000.0, d: 5.0, i:  1.0, i_clamp:   10.0, torque_clamp: 80}
    leg_left_4_joint:  &leg_4_gains {p:  3000.0, d: 5.0, i:  1.0, i_clamp:   10.0, torque_clamp: 120}
    leg_left_5_joint:  &leg_5_gains {p:  1500.0, d: 2.0, i:  1.0, i_clamp:   10.0, torque_clamp: 80}
    leg_left_6_joint:  &leg_6_gains {p:  1000.0, d: 2.0, i:  1.0, i_clamp:   10.0, torque_clamp: 60}
    leg_right_1_joint: *leg_1_gains
    leg_right_2_joint: *leg_2_gains
    leg_right_3_joint: *leg_3_gains
    leg_right_4_joint: *leg_4_gains
    leg_right_5_joint: *leg_5_gains
    leg_right_6_joint: *leg_6_gains
  joint_trajectory_action_node:
    joints: *leg_joints
    constraints:
      goal_time: *goal_time_constraint
      leg_left_1_joint:
        goal: *goal_pos_constraint
      leg_left_2_joint:
        goal: *goal_pos_constraint
      leg_left_3_joint:
        goal: *goal_pos_constraint
      leg_left_4_joint:
        goal: *goal_pos_constraint
      leg_left_5_joint:
        goal: *goal_pos_constraint
      leg_left_6_joint:
        goal: *goal_pos_constraint
      leg_right_1_joint:
        goal: *goal_pos_constraint
      leg_right_2_joint:
        goal: *goal_pos_constraint
      leg_right_3_joint:
        goal: *goal_pos_constraint
      leg_right_4_joint:
        goal: *goal_pos_constraint
      leg_right_5_joint:
        goal: *goal_pos_constraint
      leg_right_6_joint:
        goal: *goal_pos_constraint