lower_body_controller:
  type: "robot_mechanism_controllers/JointTrajectoryActionController"
  joints: &leg_joints
    - leg_left_1_joint
    - leg_left_2_joint
    - leg_left_3_joint
    - leg_left_4_joint
    - leg_left_5_joint
    - leg_left_6_joint
    - leg_right_1_joint
    - leg_right_2_joint
    - leg_right_3_joint
    - leg_right_4_joint
    - leg_right_5_joint
    - leg_right_6_joint
  gains:
    leg_left_1_joint:  &leg_1_gains {p:  1500.0, d: 2.0, i:  1.0, i_clamp:   10.0, torque_clamp: 50}
    leg_left_2_joint:  &leg_2_gains {p:  1500.0, d: 2.0, i:  1.0, i_clamp:   10.0, torque_clamp: 60}
    leg_left_3_joint:  &leg_3_gains {p:  3000.0, d: 5.0, i:  1.0, i_clamp:   10.0, torque_clamp: 80}
    leg_left_4_joint:  &leg_4_gains {p:  3000.0, d: 5.0, i:  1.0, i_clamp:   10.0, torque_clamp: 120}
    leg_left_5_joint:  &leg_5_gains {p:  1500.0, d: 2.0, i:  1.0, i_clamp:   10.0, torque_clamp: 80}
    leg_left_6_joint:  &leg_6_gains {p:  1000.0, d: 2.0, i:  1.0, i_clamp:   10.0, torque_clamp: 60}
    leg_right_1_joint: *leg_1_gains
    leg_right_2_joint: *leg_2_gains
    leg_right_3_joint: *leg_3_gains
    leg_right_4_joint: *leg_4_gains
    leg_right_5_joint: *leg_5_gains
    leg_right_6_joint: *leg_6_gains
  joint_trajectory_action_node:
    joints: *leg_joints
    constraints:
      goal_time: &goal_time_constraint 0.6
      leg_left_1_joint:
        goal: &goal_pos_constraint 0.02
      leg_left_2_joint:
        goal: *goal_pos_constraint
      leg_left_3_joint:
        goal: *goal_pos_constraint
      leg_left_4_joint:
        goal: *goal_pos_constraint
      leg_left_5_joint:
        goal: *goal_pos_constraint
      leg_left_6_joint:
        goal: *goal_pos_constraint
      leg_right_1_joint:
        goal: *goal_pos_constraint
      leg_right_2_joint:
        goal: *goal_pos_constraint
      leg_right_3_joint:
        goal: *goal_pos_constraint
      leg_right_4_joint:
        goal: *goal_pos_constraint
      leg_right_5_joint:
        goal: *goal_pos_constraint
      leg_right_6_joint:
        goal: *goal_pos_constraint